name: Restart DEV Platform

on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: SSH into server and run restart script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST_DEV}}
          username: ${{ secrets.SSH_USER_DEV }}
          key: ${{ secrets.DEPLOY_KEY_DEV }}
          passphrase: ${{ secrets.DEPLOY_KEY_PASS_DEV }}
          script: sudo bash /home/sari/scripts/restartPlatform.sh
          
